name: Slack Notification Workflow

on:
  workflow_call:
    inputs:
      exitCode:
        required: true
        type: string
      slackChannelId:
        required: true
        type: string
      payloadFile:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    # outputs:
    #   SlackBotToken: ${{ steps.setup.outputs.SlackBotToken }}
    #   SlackChannelId: ${{ steps.setup.outputs.SlackChannelId }}
    #   ExitCode: ${{ steps.setup.outputs.ExitCode }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Setup
      #   id: setup
      #   run: |
      #     echo "SlackChannelId=${{ github.event.inputs.slackChannelId }}" >> "$GITHUB_OUTPUT"
      #     echo "ExitCode=${{ github.event.inputs.exitCode }}" >> "$GITHUB_OUTPUT"

      # - name: Read payload file
      #   id: read-payload
      #   run: |
      #     payload=$(cat ${{ github.event.inputs.payloadFile }})
      #     echo "payload=$payload" >> $GITHUB_ENV
      
      - name: Replace placeholder
        run: |
          cat "${{ github.event.inputs.payloadFile }}" | envsubst > translated_payload.json ; echo $?
          cat ./translated_payload.json | jq -c ; echo $?
          echo "message=$(cat ./translated_payload.json | jq -c)"  >> $GITHUB_ENV

      - name: Notify Slack - Success
        # if: ${{ steps.setup.outputs.ExitCode == '0' }}
        if: ${{ github.event.inputs.exitCode == '0' }}
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN_GITHUB_NOTIFY }}
        with:
          # channel-id: ${{ github.event.inputs.slackChannelId }}
          channel-id: ${{ vars.SLACK_NOTIFY_CHANNEL_ID }}
          payload: ${{ github.env.message }}
    
      - name: Notify Slack - Failure
        if: ${{ github.event.inputs.exitCode != '0' }}
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN_GITHUB_NOTIFY }}
        with:
          # channel-id: ${{ github.event.inputs.slackChannelId }}
          channel-id: ${{ vars.SLACK_NOTIFY_CHANNEL_ID }}
          payload: |
            ${{ github.env.message }}
    