name: Slack Notification Workflow

on:
  workflow_call:
    inputs:
      exitCode:
        required: true
        type: string
      slackChannelId:
        required: true
        type: string
      payloadFile:
        required: true
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Replace placeholder
        run: |
          cat "${{ inputs.payloadFile }}" | envsubst > translated_payload.json ; echo $?
          cat ./translated_payload.json | jq -c ; echo $?
          echo "message=$(cat ./translated_payload.json | jq -c)"  >> $GITHUB_ENV

      - name: Notify Slack - Success
        # if: ${{ steps.setup.outputs.ExitCode == '0' }}
        if: ${{ inputs.exitCode == 'success' }}
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN_GITHUB_NOTIFY }}
        with:          
          channel-id: ${{ vars.SLACK_NOTIFY_CHANNEL_ID }}
          payload: |
            {
              "text": "GitHub Action build result.....",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":white_check_mark:[${{ github.repository }}] ${{ github.workflow }} Succeeded.",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow*: <https://github.com/${{ github.repository }}/actions/|${{ github.workflow }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Status*: ${{ inputs.exitCode }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "成果物はArtifactsにアップロードしました. <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id}}/|GitHub Artifacts>から確認できます"
                  }
                }
              ]
            }

          
      - name: Notify Slack - Failure
        # if: ${{ github.event.inputs.exitCode != '0' }}
        if: ${{ github.event.inputs.exitCode != 'success' }}
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN_GITHUB_NOTIFY }}
        with:
          # channel-id: ${{ github.event.inputs.slackChannelId }}
          channel-id: ${{ vars.SLACK_NOTIFY_CHANNEL_ID }}
          payload: |
            {
              "text": "GitHub Action build result.....",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":no_entry_sign:[${{ github.repository }}] ${{ github.workflow }} Failure.",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow*: <https://github.com/${{ github.repository }}/actions/|${{ github.workflow }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Status*: ${{ inputs.exitCode }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "エラー内容は<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/|actions #${{ github.run_id }}>から確認できます"
                  }
                }
              ]
            }    