name: Slack Notification Workflow

on:
  workflow_call:
    inputs:
      slack-bot-token:
        required: true
        type: string
      slack-channel-id:
        required: true
        type: string
      event-type:
        required: true
        type: string
      event-exit-code:
        required: true
        type: string


jobs:
  setup_variables:
    runs-on: ubuntu-latest
    outputs:
      SlackBotToken: ${{ steps.setup.outputs.SlackBotToken }}
      SlackChannelId: ${{ steps.setup.outputs.SlackChannelId }}
      EventType: ${{ steps.setup.outputs.EventType }}
      ExitCode: ${{ steps.setup.outputs.ExitCode }}
    steps:
    # inputs.slack-bot-tokenをマスキングしつつSLACK_BOT_TOKEN変数に使う
      - name: Setup
        id: setup
        run: |
          echo "::add-mask::${{ inputs.slack-bot-token }}"
          echo "SlackBotToken=${{ inputs.slack-bot-token }}" >> "$GITHUB_OUTPUT"
          echo "SlackChannelId=${{ inputs.slack-slack-channel-id }}" >> "$GITHUB_OUTPUT"
          echo "EventType=${{ inputs.event-type }}" >> "$GITHUB_OUTPUT"
          echo "ExitCode=${{ inputs.event-exit-code }}" >> "$GITHUB_OUTPUT"

  notify_failure:
    runs-on: ubuntu-latest
    needs: setup_variables
    env:
      SLACK_BOT_TOKEN: ${{ needs.setup_variables.outputs.SlackBotToken }}
    if: ${{ needs.setup_variables.outputs.ExitCode == '1' }}
    steps:
      - name: Notify failure to a Slack channel
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: ${{ needs.setup_variables.outputs.SlackChannelId }}
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":no_entry_sign:[${{ github.repository }}] ビルド失敗",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow*: <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.event.inputs.event-type }}>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Status*: ${{ job.status }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*: <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "ビルドに失敗しています、エラー内容は <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|actions #${{ github.run_id }}> から確認できます"
                  }
                }
              ]
            }
