name: test dispatch event

on:
  workflow_dispatch:
    inputs:
      payloadFile:
        description: 'Path to payload file'
        required: true
        default: '.github/workflows/success_payload.json'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      exitCode: ${{ steps.saveExitCode.exitCode }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

    # 他のステップがここに追加される

      - name: Save exitCode
        id: saveExitCode
        run: |
          if ${{ steps.checkout.conclusion }} == 'success'; then
            echo "exitCode=0" >> $GITHUB_OUTPUT
          else
            echo "exitCode=1" >> $GITHUB_OUTPUT
          fi

  call_SlackNotify:
    needs: setup
    uses: terusaku/etc_public/.github/workflows/slack_notify.yml@feat/workflow_SlackNotify
    with:
      exitCode: ${{ needs.setup.outputs.exitCode }}
      slackChannelId: ${{ vars.SLACK_NOTIFY_CHANNEL_ID }}
      payloadFile: ${{ inputs.payloadFile }}
  